name: Build and Deploy (Web + Backend) to Azure Web App - dangunland

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  DEPLOY_DIR: deploy

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install (workspaces)
        run: npm install

      # Build the web (assumes root script builds shared-ui then web)
      - name: Build web
        run: npm run build:web || npm run build

      - name: Prepare deploy folder
        run: |
          set -e
          rm -rf "${DEPLOY_DIR}"
          mkdir -p "${DEPLOY_DIR}/backend/dist"
          # Copy backend runtime code
          cp -R backend/src "${DEPLOY_DIR}/backend/"
          cp backend/package.json "${DEPLOY_DIR}/backend/"
          # Copy built web assets into backend/dist (server looks there first)
          if [ -d web/dist ]; then
            cp -R web/dist/* "${DEPLOY_DIR}/backend/dist/"
          else
            echo "ERROR: web/dist not found. Build step failed?"
            exit 1
          fi
          # Optional: include root package.json only if Azure starts from root
          cp package.json "${DEPLOY_DIR}/" || true
          echo "Contents of deploy folder:"
          find "${DEPLOY_DIR}" -maxdepth 4 -type f | sed 's/^/  /'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy
          path: ${{ env.DEPLOY_DIR }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy
          path: .

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dangunland'
          slot-name: 'Production'
          package: .